nvram: simulate hobgoblin nvemu
Add a simulation of the Codasip Hobgoblin Non-Volatile Emulator Block.
It consists of two registers (status, config) and an nvram area of 0xC00 bytes.

The caller must provide the nvram content as a binary file. We use
memory-backend-file to convert the file into a memory region.

Unfortunately, memory-backend-file requires that the input file's length
is a multiple of the host memory's page size (usually 4k). This isn't
easy to change without breaking other parts of qemu. For now, we add 1k
padding after the actual nvram image. The padding is stripped before
mapping the file.

As most users are not interested in nvemu, leaving nvemu unconfigured
should not prevent qemu from starting. If no nvram image file is given on
the command line, the nvemu device can't be realized. This error is
ignored during hobgoblin setup.

Here's a sample run that adds padding to the nvram image and passes it to
qemu:

[martin.kaiser@nb282 qemu]$ dd if=/dev/zero of=./null_bytes bs=1K count=1 && \
   cat ./nvw.bin ./null_bytes > ./tmp_image && \
   ./build/qemu-system-riscv64cheri -smp 1 -cpu codasip-a730,m_flip=off \
      -M hobgoblin-genesys2,boot-from-rom=true -nographic \
      -bios ./test_rom.bin \
      -global hobgoblin-nvemu.memdev=mb0 \
      -object memory-backend-file,id=mb0,size=0x1000,mem-path=./tmp_image

1+0 records in
1+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.000222637 s, 4.6 MB/s

 info:    __________  ____  ___   _____ ________
 info:   / ____/ __ \/ __ \/   | / ___//  _/ __ \
 info:  / /   / / / / / / / /| | \__ \ / // /_/ /
 info: / /___/ /_/ / /_/ / ___ |___/ // // ____/
 info: \____/\____/_____/_/__|_/____/___/_/_
 info:   / ___// __ )_  __/ ____/ ___/_  __/
 info:   \__ \/ __  |/ / / __/  \__ \ / /
 info:  ___/ / /_/ // / / /___ ___/ // /
 info: /____/_____//_/ /_____//____//_/

 info: =========================================

/shared_home/repo/src/firmware/test/test.c:163:test_memset_zero:PASS
...
/shared_home/repo/src/firmware/test/test.c:202:test_sb_get_auth_enable:PASS

-----------------------
39 Tests 0 Failures 0 Ignored
OK
error: Exit called with exitcode (0)
QEMU: Terminated
[martin.kaiser@nb282 qemu]$